sudo: required

language: generic

services:
  - docker


before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t seooo/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true seooo/docker-react-app npm run test -- --coverage

after_sucess:
  - echo "Test success"